name: Deploy to Render (PROD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_PROD }}"
